# Generated by Django 4.2 on 2024-04-09 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0002_alter_film_genres"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="genres",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profiles",
                related_query_name="profiles",
                to="films.genre",
            ),
            preserve_default=False,
        ),
    ]
