# Generated by Django 4.2 on 2024-04-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0002_alter_film_genres"),
        ("users", "0002_profile_genres"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="genres",
        ),
        migrations.AddField(
            model_name="profile",
            name="genres",
            field=models.ManyToManyField(
                related_name="profiles", related_query_name="profiles", to="films.genre"
            ),
        ),
    ]
