# Generated by Django 4.2 on 2024-04-09 16:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0001_initial"),
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Rows",
            new_name="Row",
        ),
        migrations.CreateModel(
            name="FilmSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(verbose_name="Дата и время начала сеанса"),
                ),
                (
                    "price",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Цена билета",
                    ),
                ),
                (
                    "auditorium",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="timetable.auditorium",
                        verbose_name="зал",
                    ),
                ),
                (
                    "film",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="films.film",
                        verbose_name="фильм",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сеанс",
                "verbose_name_plural": "Сеансы",
                "db_table": "timetable_film_sessions",
            },
        ),
    ]
