# Generated by Django 4.2 on 2024-04-09 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0002_alter_film_genres"),
        ("timetable", "0002_rename_rows_row_filmsession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filmsession",
            name="auditorium",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                related_query_name="sessions",
                to="timetable.auditorium",
                verbose_name="Зал",
            ),
        ),
        migrations.AlterField(
            model_name="filmsession",
            name="film",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                related_query_name="sessions",
                to="films.film",
                verbose_name="Фильм",
            ),
        ),
        migrations.AlterField(
            model_name="row",
            name="auditorium",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rows",
                related_query_name="rows",
                to="timetable.auditorium",
                verbose_name="Зал",
            ),
        ),
    ]
