# Generated by Django 4.2 on 2024-04-14 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "timetable",
            "0003_alter_filmsession_auditorium_alter_filmsession_film_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="row",
            name="auditorium",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rows",
                related_query_name="rows",
                to="timetable.auditorium",
                verbose_name="Зал",
            ),
        ),
    ]
