# Generated by Django 4.2 on 2024-04-20 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0005_filmsession_end_datetime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auditorium",
            name="row_count",
        ),
    ]
