# Generated by Django 4.2 on 2024-04-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="genres",
            field=models.ManyToManyField(
                help_text="Жанры фильма",
                related_name="films",
                related_query_name="films",
                to="films.genre",
                verbose_name="Жанры",
            ),
        ),
    ]
