# Generated by Django 4.2 on 2024-04-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0002_alter_film_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="description",
            field=models.CharField(
                default="", help_text="Описание фильма", max_length=1000
            ),
            preserve_default=False,
        ),
    ]
