# Generated by Django 4.2 on 2024-04-17 13:08

from django.db import migrations, models
import films.models


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0003_film_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=films.models.Film.get_upload_path,
                verbose_name="Изображение фильма",
            ),
        ),
    ]
