# Generated by Django 4.2 on 2024-04-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0004_film_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="age_limit",
            field=models.CharField(
                choices=[
                    ["0+", "0+"],
                    ["6+", "0+"],
                    ["12+", "12+"],
                    ["16+", "16+"],
                    ["18+", "18+"],
                ],
                default="12+",
                help_text="Возрастное ограничение",
                max_length=3,
            ),
            preserve_default=False,
        ),
    ]
