# Generated by Django 4.2 on 2024-04-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0005_film_age_limit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Имя актера", max_length=100, verbose_name="Имя"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Фамилия актера",
                        max_length=100,
                        verbose_name="Фамилия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Актер",
                "verbose_name_plural": "Актеры",
                "db_table": "films_actors",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название страны",
                        max_length=500,
                        verbose_name="Название",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страна",
                "verbose_name_plural": "Страны",
                "db_table": "films_countries",
            },
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Имя режиссера", max_length=100, verbose_name="Имя"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Фамилия режиссера",
                        max_length=100,
                        verbose_name="Фамилия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Режиссер",
                "verbose_name_plural": "Режиссеры",
                "db_table": "films_directors",
            },
        ),
        migrations.AddField(
            model_name="film",
            name="actors",
            field=models.ManyToManyField(
                related_name="actor_films",
                related_query_name="actor_films",
                to="films.actor",
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="countries",
            field=models.ManyToManyField(
                related_name="country_films",
                related_query_name="country_films",
                to="films.director",
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="directors",
            field=models.ManyToManyField(
                related_name="director_films",
                related_query_name="director_films",
                to="films.director",
            ),
        ),
    ]
