# Generated by Django 4.2 on 2024-04-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0006_actor_country_director_film_actors_film_countries_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="countries",
            field=models.ManyToManyField(
                related_name="country_films",
                related_query_name="country_films",
                to="films.country",
            ),
        ),
    ]
