# Generated by Django 4.2 on 2024-04-26 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_film_genres_squashed_0007_alter_film_countries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'актер', 'verbose_name_plural': 'Актеры'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={
                'verbose_name': 'страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.AlterModelOptions(
            name='director',
            options={
                'verbose_name': 'режиссер',
                'verbose_name_plural': 'Режиссеры',
            },
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'жанр', 'verbose_name_plural': 'Жанры'},
        ),
    ]
