# Generated by Django 4.2 on 2024-04-09 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tickets", "0001_initial"),
        ("timetable", "0002_rename_rows_row_filmsession"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="session_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                related_query_name="tickets",
                to="timetable.filmsession",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                related_query_name="tickets",
                to="users.profile",
            ),
        ),
    ]
