# Generated by Django 4.2 on 2024-04-09 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="session_id",
            new_name="session",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="user_id",
            new_name="user",
        ),
    ]
