# Generated by Django 4.2 on 2024-04-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_rename_session_id_ticket_session_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="user",
            new_name="profile",
        ),
    ]
