# Generated by Django 4.2 on 2024-04-20 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_rename_user_ticket_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"verbose_name": "Билет", "verbose_name_plural": "Билеты"},
        ),
        migrations.AlterModelTable(
            name="ticket",
            table="tickets_ticket",
        ),
    ]
