# Generated by Django 4.2 on 2024-04-20 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0006_remove_auditorium_row_count"),
        ("users", "0003_remove_profile_genres_profile_genres"),
        ("tickets", "0005_alter_ticket_options_alter_ticket_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="session",
        ),
        migrations.AlterModelTable(
            name="ticket",
            table="tickets_tickets",
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime_order",
                    models.DateField(
                        help_text="Дата и время оформления заказа",
                        verbose_name="Дата и время оформления заказа",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        related_query_name="orders",
                        to="users.profile",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        related_query_name="orders",
                        to="timetable.filmsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "db_table": "tickets_orders",
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="order",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                related_query_name="tickets",
                to="tickets.order",
            ),
            preserve_default=False,
        ),
    ]
