# Generated by Django 4.2 on 2024-04-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0006_remove_ticket_profile_remove_ticket_session_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="datetime_order",
            field=models.DateTimeField(
                help_text="Дата и время оформления заказа",
                verbose_name="Дата и время оформления заказа",
            ),
        ),
    ]
